// Code generated by "stringer -type=FsEventType -linecomment"; DO NOT EDIT.

package fswatch

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FsEventTypeNoOp-0]
	_ = x[FsEventTypePlatformSpecific-1]
	_ = x[FsEventTypeCreated-2]
	_ = x[FsEventTypeUpdated-3]
	_ = x[FsEventTypeRemoved-4]
	_ = x[FsEventTypeRenamed-5]
	_ = x[FsEventTypeOwnerModified-6]
	_ = x[FsEventTypeAttributeModified-7]
	_ = x[FsEventTypeMovedFrom-8]
	_ = x[FsEventTypeMovedTo-9]
	_ = x[FsEventTypeIsFile-10]
	_ = x[FsEventTypeIsDir-11]
	_ = x[FsEventTypeIsSymLink-12]
	_ = x[FsEventTypeLink-13]
	_ = x[FsEventTypeOverflow-14]
}

const _FsEventType_name = "NoOpPlatformSpecificCreatedUpdatedRemovedRenamedOwnerModifiedAttributeModifiedMovedFromMovedToIsFileIsDirIsSymLinkLinkOverflow"

var _FsEventType_index = [...]uint8{0, 4, 20, 27, 34, 41, 48, 61, 78, 87, 94, 100, 105, 114, 118, 126}

func (i FsEventType) String() string {
	if i >= FsEventType(len(_FsEventType_index)-1) {
		return "FsEventType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FsEventType_name[_FsEventType_index[i]:_FsEventType_index[i+1]]
}
