// Code generated by interfacer; DO NOT EDIT

package interfaces

import (
	"context"
)

// CgroupMonitor is an interface generated for "github.com/black-desk/cgtproxy/internal/cgmon.FSMonitor".
type CgroupMonitor interface {
	Run(context.Context) error
}
