// Code generated by interfacer; DO NOT EDIT

package interfaces

import (
	"context"
)

// CGTProxy is an interface generated for "github.com/black-desk/cgtproxy/pkg/cgtproxy.CGTProxy".
type CGTProxy interface {
	Delete() error
	RunCGTProxy(context.Context) error
}
