// Code generated by interfacer; DO NOT EDIT

package interfaces

import (
	"github.com/black-desk/cgtproxy/pkg/cgtproxy/config"
	"github.com/black-desk/cgtproxy/pkg/types"
)

// NFTManager is an interface generated for "github.com/black-desk/cgtproxy/pkg/nftman.NFTManager".
type NFTManager interface {
	AddChainAndRulesForTProxies([]*config.TProxy) error
	AddRoutes([]types.Route) error
	Clear() error
	InitStructure() error
	Release() error
	RemoveRoutes([]string) error
}
