// Code generated by interfacer; DO NOT EDIT

package interfaces

import ()

// RouteManager is an interface generated for "github.com/black-desk/cgtproxy/pkg/routeman.RouteManager".
type RouteManager interface {
	Run() error
}
