// Code generated by interfacer; DO NOT EDIT

package interfaces

import (
	"context"
)

// RouteManager is an interface generated for "github.com/black-desk/cgtproxy/pkg/routeman.RouteManager".
type RouteManager interface {
	RunRouteManager(context.Context) error
}
