// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package nftman

import (
	"github.com/black-desk/cgtproxy/internal/tests/logger"
	"github.com/black-desk/cgtproxy/pkg/cgtproxy/config"
)

// Injectors from wire.go:

func injectedNFTManagerWithLastingConnector(cGroupRoot config.CGroupRoot) (*NFTManager, error) {
	sugaredLogger, err := logger.ProvideLogger()
	if err != nil {
		return nil, err
	}
	netlinkConnector, err := provideLastingConnector()
	if err != nil {
		return nil, err
	}
	nftManager, err := provideNFTManager(cGroupRoot, sugaredLogger, netlinkConnector)
	if err != nil {
		return nil, err
	}
	return nftManager, nil
}

func injectedNFTManagerWithConnector(cGroupRoot config.CGroupRoot) (*NFTManager, error) {
	sugaredLogger, err := logger.ProvideLogger()
	if err != nil {
		return nil, err
	}
	netlinkConnector, err := provideLastingConnector()
	if err != nil {
		return nil, err
	}
	nftManager, err := provideNFTManager(cGroupRoot, sugaredLogger, netlinkConnector)
	if err != nil {
		return nil, err
	}
	return nftManager, nil
}
