// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package tabletest

import (
	"github.com/google/nftables"
)

// Injectors from wire.go:

func InjectedConn() (*nftables.Conn, error) {
	conn, err := provideNftConn()
	if err != nil {
		return nil, err
	}
	return conn, nil
}
