// Code generated by "stringer -type=cgroupEventType -linecomment"; DO NOT EDIT.

package core

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[cgroupEventTypeNew-0]
}

const _cgroupEventType_name = "New"

var _cgroupEventType_index = [...]uint8{0, 3}

func (i cgroupEventType) String() string {
	if i >= cgroupEventType(len(_cgroupEventType_index)-1) {
		return "cgroupEventType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _cgroupEventType_name[_cgroupEventType_index[i]:_cgroupEventType_index[i+1]]
}
