// Code generated by "stringer -type=CgroupEventType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CgroupEventTypeNew-0]
	_ = x[CgroupEventTypeDelete-1]
}

const _CgroupEventType_name = "NewDelete"

var _CgroupEventType_index = [...]uint8{0, 3, 9}

func (i CgroupEventType) String() string {
	if i >= CgroupEventType(len(_CgroupEventType_index)-1) {
		return "CgroupEventType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CgroupEventType_name[_CgroupEventType_index[i]:_CgroupEventType_index[i+1]]
}
