// Code generated by "stringer -type=TargetOp -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TargetNoop-0]
	_ = x[TargetDrop-1]
	_ = x[TargetTProxy-2]
	_ = x[TargetDirect-3]
}

const _TargetOp_name = "noopdroptproxydirect"

var _TargetOp_index = [...]uint8{0, 4, 8, 14, 20}

func (i TargetOp) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_TargetOp_index)-1 {
		return "TargetOp(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TargetOp_name[_TargetOp_index[idx]:_TargetOp_index[idx+1]]
}
